.TH "include Directory Reference" 3 "Tue Sep 10 2013" "Version 1" "HMC_BNN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBNN_regression\&.h\fP"
.br
.ti -1c
.RI "file \fBdefine_type\&.h\fP"
.br
.ti -1c
.RI "file \fBHMC_base\&.h\fP"
.br
.ti -1c
.RI "file \fBHMC_dist\&.h\fP"
.br
.in -1c
