.TH "src/HMClib Directory Reference" 3 "Wed May 29 2013" "Version 1" "HMC_BNN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/HMClib Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBNN_regression\&.cc\fP"
.br
.ti -1c
.RI "file \fBHMC\&.cxx\fP"
.br
.ti -1c
.RI "file \fBHMC_base\&.cc\fP"
.br
.ti -1c
.RI "file \fBMCMC_base\&.cxx\fP"
.br
.in -1c
