.TH "src/BNN_regression.cc" 3 "Tue Sep 10 2013" "Version 1" "HMC_BNN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/BNN_regression.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'BNN_regression\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br

.SH "Detailed Description"
.PP 

.PP
.PP
\fBAuthor:\fP
.RS 4
Michelle E\&. Perry 
.RE
.PP
\fBDate:\fP
.RS 4
created 25/2/2013 updated 9/9/2013 
.RE
.PP

.PP
Definition in file \fBBNN_regression\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HMC_BNN from the source code\&.
