.TH "include/BNN_regression.h" 3 "Tue Sep 10 2013" "Version 1" "HMC_BNN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/BNN_regression.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'HMC_base\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBNN_regression\fP"
.br
.RI "\fIBNN functional approximation class\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HMC_BNN from the source code\&.
