.TH "include/define_type.h" 3 "Tue Sep 10 2013" "Version 1" "HMC_BNN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/define_type.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef float \fBHMC_type\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef float \fBHMC_type\fP"

.PP
Definition at line 4 of file define_type\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HMC_BNN from the source code\&.
