.TH "src/HMC.cxx" 3 "Tue Sep 10 2013" "Version 1" "HMC_BNN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/HMC.cxx \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'HMC\&.h'\fP
.br
\fC#include 'probDist\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< float > \fBHMC\fP (float eps, int L, std::vector< float > &q0)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::vector<float> HMC (floateps, intL, std::vector< float > &q0)"

.PP
Definition at line 6 of file HMC\&.cxx\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HMC_BNN from the source code\&.
