.TH "include/HMC_base.h" 3 "Tue Sep 10 2013" "Version 1" "HMC_BNN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/HMC_base.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'define_type\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBHMC_base\fP"
.br
.RI "\fIBase Hybrid Monte Carlo class\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HMC_BNN from the source code\&.
