.TH "src/MCMC_base.cxx" 3 "Mon Sep 9 2013" "Version 1" "HMC_BNN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MCMC_base.cxx \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'MCMC_base\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for HMC_BNN from the source code\&.
