.TH "src/multidimprob.cc" 3 "Tue Sep 10 2013" "Version 1" "HMC_BNN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/multidimprob.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'HMC_dist\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for HMC_BNN from the source code\&.
