HMC_BNN: HMC_dist Class Reference
HMC_dist Class Reference
probability distribution class
#include "HMC_dist.h"
Public Member Functions
HMC_dist (int l, int nParams)
virtual HMC_type U (std::vector< HMC_type > &)
U = -ln(P(q))
virtual std::vector< HMC_type > delU (std::vector< HMC_type > &)
calculate dU */
std::vector< HMC_type > FD (std::vector< HMC_type > &q)
Public Member Functions inherited from HMC_base
HMC_base (int l, int nParams)
virtual ~HMC_base ()
int getNP ()
getter for NP variable in derived classes
std::vector< HMC_type > & it (std::vector< HMC_type > &)
one HMC iteration
Detailed Description
probability distribution class
Author
Michelle E. Perry
Date
created 21/2/13 updated
Definition at line 15 of file HMC_dist.h.
Constructor & Destructor Documentation
HMC_dist::HMC_dist (int l, int nParams) inline
Definition at line 17 of file HMC_dist.h.
Member Function Documentation
std::vector< HMC_type > HMC_dist::delU (std::vector< HMC_type > &) virtual
calculate dU */
Implements HMC_base.
Definition at line 39 of file multidimprob.cc.
References FD().
std::vector<HMC_type> HMC_dist::FD (std::vector< HMC_type > & q) inline
Definition at line 25 of file HMC_dist.h.
References HMC_base::q, and U().
Referenced by delU().
HMC_type HMC_dist::U (std::vector< HMC_type > & q) virtual
U = -ln(P(q))
Implements HMC_base.
Definition at line 5 of file multidimprob.cc.
Referenced by FD().
The documentation for this class was generated from the following files:
include/HMC_dist.h
src/multidimprob.cc