HMC_BNN: HMC_base Class Reference
HMC_base Class Reference abstract
Base Hybrid Monte Carlo class.
#include "HMC_base.h"
Public Member Functions
HMC_base (int l, int nParams)
virtual ~HMC_base ()
int getNP ()
getter for NP variable in derived classes
std::vector< HMC_type > & it (std::vector< HMC_type > &)
one HMC iteration
virtual HMC_type U (std::vector< HMC_type > &)=0
calculate U
virtual std::vector< HMC_type > delU (std::vector< HMC_type > &)=0
calculate dU */
Private Member Functions
std::vector< HMC_type > calc_step (std::vector< HMC_type > &q)
calculates step size each HMC iteration
Private Attributes
int L
number of steps in one HMC iteration
int NP
number of parameters
HMC_type Uq0
potential at current point
std::vector< HMC_type > q
class parameters definition to avoid many re-allocations in loops
std::vector< HMC_type > p
class momentum definition to avoid many re-allocations in loops
Detailed Description
Base Hybrid Monte Carlo class.
Author
Michelle E. Perry
Date
created 6/6/2013 updated 9/9/2013
Definition at line 14 of file HMC_base.h.
Constructor & Destructor Documentation
HMC_base::HMC_base (int l, int nParams) inline
Definition at line 22 of file HMC_base.h.
virtual HMC_base::~HMC_base () inline virtual
Definition at line 29 of file HMC_base.h.
Member Function Documentation
std::vector< HMC_type > HMC_base::calc_step (std::vector< HMC_type > & q) private
calculates step size each HMC iteration
Definition at line 7 of file HMC_base.cc.
References NP, q, U(), and Uq0.
Referenced by it().
virtual std::vector<HMC_type> HMC_base::delU (std::vector< HMC_type > &) pure virtual
calculate dU */
Implemented in BNN_regression, and HMC_dist.
Referenced by it().
int HMC_base::getNP ()
getter for NP variable in derived classes
Definition at line 151 of file HMC_base.cc.
References NP.
Referenced by BNN_regression::U().
std::vector< HMC_type > & HMC_base::it (std::vector< HMC_type > & q0)
one HMC iteration
< Uq0 calculated in this function
Definition at line 46 of file HMC_base.cc.
References calc_step(), delU(), L, NP, p, q, U(), and Uq0.
virtual HMC_type HMC_base::U (std::vector< HMC_type > &) pure virtual
calculate U
Implemented in BNN_regression, and HMC_dist.
Referenced by calc_step(), and it().
Field Documentation
int HMC_base::L private
number of steps in one HMC iteration
Definition at line 15 of file HMC_base.h.
Referenced by it().
int HMC_base::NP private
number of parameters
Definition at line 16 of file HMC_base.h.
Referenced by calc_step(), getNP(), and it().
std::vector<HMC_type> HMC_base::p private
class momentum definition to avoid many re-allocations in loops
Definition at line 20 of file HMC_base.h.
Referenced by it().
std::vector<HMC_type> HMC_base::q private
class parameters definition to avoid many re-allocations in loops
Definition at line 19 of file HMC_base.h.
Referenced by calc_step(), HMC_dist::FD(), and it().
HMC_type HMC_base::Uq0 private
potential at current point
Definition at line 17 of file HMC_base.h.
Referenced by calc_step(), and it().
The documentation for this class was generated from the following files:
include/HMC_base.h
src/HMC_base.cc